service: superApp

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    stage: ${self:provider.stage}

functions:
  graphql:
    handler: functions/graphql/index.handler
    events:
      - http:
          path: /graphql
          method: any
          cors: true

plugins:
  - serverless-offline
